dotnet test Tests\qshine.Tests
dotnet test qshine.extension\Tests\qshine.autofac.Tests
dotnet test qshine.extension\Tests\qshine.log.nlog.Tests
dotnet test qshine.extension\Tests\qshine.json.newton.Tests
dotnet test database\tests\qshine.database.mysql.Tests
dotnet test database\tests\qshine.database.sqlite.Tests
dotnet test database\tests\qshine.database.oracle.Tests
dotnet test database\tests\qshine.database.postgresql.Tests
dotnet test database\tests\qshine.database.sqlserver.Tests