//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qshine.Globalization 
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("qshine.Globalization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required but was null or empty..
        /// </summary>
        internal static string ArgumentNotEmpty {
            get {
                return ResourceManager.GetString("ArgumentNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required but was null..
        /// </summary>
        internal static string ArgumentNotNULL {
            get {
                return ResourceManager.GetString("ArgumentNotNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.Add:dependencies must be null..
        /// </summary>
        internal static string CacheAddDependenciesNotSupportedException {
            get {
                return ResourceManager.GetString("CacheAddDependenciesNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.Add:onRemoveCallback must be null..
        /// </summary>
        internal static string CacheAddOnRemoveCallbackNotSupport {
            get {
                return ResourceManager.GetString("CacheAddOnRemoveCallbackNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field value must be a date between {1} and {2}..
        /// </summary>
        internal static string DateFieldRangeMessage {
            get {
                return ResourceManager.GetString("DateFieldRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add same rule {0} twice..
        /// </summary>
        internal static string DuplicateRules {
            get {
                return ResourceManager.GetString("DuplicateRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be a valid {1}..
        /// </summary>
        internal static string FieldDataTypeMessage {
            get {
                return ResourceManager.GetString("FieldDataTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field size should be limited between {1} to {2} characters..
        /// </summary>
        internal static string FieldLengthMessage {
            get {
                return ResourceManager.GetString("FieldLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field characters could not exceed {1} characters..
        /// </summary>
        internal static string FieldMaxLengthMessage {
            get {
                return ResourceManager.GetString("FieldMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field value is required..
        /// </summary>
        internal static string FieldRequiredMessage {
            get {
                return ResourceManager.GetString("FieldRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in Enterprise Library Logging Application Block.
        /// </summary>
        internal static string LoggingException {
            get {
                return ResourceManager.GetString("LoggingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field value must be a number between {1} and {2}..
        /// </summary>
        internal static string NumericFieldRangeMessage {
            get {
                return ResourceManager.GetString("NumericFieldRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AddRules method takes at least one argument..
        /// </summary>
        internal static string OneRuleRequired {
            get {
                return ResourceManager.GetString("OneRuleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Validation Failed..
        /// </summary>
        internal static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }


		/// <summary>
		///   Looks up a localized string similar to The IoC provider {0} is not found..
		/// </summary>
		public static string IoCExceptionProviderNotFound
		{
			get
			{
				return ResourceManager.GetString("IoCExceptionProviderNotFound", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to IoC error occured while trying register a type {0}..
		/// </summary>
		public static string IoCExceptionRegisterMessage
		{
			get
			{
				return ResourceManager.GetString("IoCExceptionRegisterMessage", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to IoC error occurred while trying to register a module..
		/// </summary>
		public static string IoCExceptionRegisterModuleMessage
		{
			get
			{
				return ResourceManager.GetString("IoCExceptionRegisterModuleMessage", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to IoC error occured while trying register a type {0} with a name {1}..
		/// </summary>
		public static string IoCExceptionRegisterNameMessage
		{
			get
			{
				return ResourceManager.GetString("IoCExceptionRegisterNameMessage", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Castle Windsor configuration registration should be done earlier than  any other type registration..
		/// </summary>
		public static string IoCExceptionRegisterSectionFirstMessage
		{
			get
			{
				return ResourceManager.GetString("IoCExceptionRegisterSectionFirstMessage", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to IoC error occured while trying to register types through a XML configuration section {0}. .
		/// </summary>
		public static string IoCExceptionRegisterSectionMessage
		{
			get
			{
				return ResourceManager.GetString("IoCExceptionRegisterSectionMessage", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to IoC error occured while trying to resolve all registered type {0}..
		/// </summary>
		public static string IoCExceptionResolveAllMessage
		{
			get
			{
				return ResourceManager.GetString("IoCExceptionResolveAllMessage", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to IoC error occured while trying to resolve type {0}..
		/// </summary>
		public static string IoCExceptionResolveMessage
		{
			get
			{
				return ResourceManager.GetString("IoCExceptionResolveMessage", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to IoC error occured while trying to resolve type {0} with a specific name {1}..
		/// </summary>
		public static string IoCExceptionResolveNamedMessage
		{
			get
			{
				return ResourceManager.GetString("IoCExceptionResolveNamedMessage", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The section {0} is not found. Check the section name and section handler type..
		/// </summary>
		public static string SectionNotFound
		{
			get
			{
				return ResourceManager.GetString("SectionNotFound", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The type {0} is not found..
		/// </summary>
		public static string TypeNotFound
		{
			get
			{
				return ResourceManager.GetString("TypeNotFound", resourceCulture);
			}
		}
    }
}
