//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qshine.ioc.autofac.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("qshine.ioc.autofac.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IoC provider {0} is not found..
        /// </summary>
        internal static string IoCExceptionProviderNotFound {
            get {
                return ResourceManager.GetString("IoCExceptionProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoC error occured while trying register a type {0}..
        /// </summary>
        internal static string IoCExceptionRegisterMessage {
            get {
                return ResourceManager.GetString("IoCExceptionRegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoC error occurred while trying to register a module..
        /// </summary>
        internal static string IoCExceptionRegisterModuleMessage {
            get {
                return ResourceManager.GetString("IoCExceptionRegisterModuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoC error occured while trying register a type {0} with a name {1}..
        /// </summary>
        internal static string IoCExceptionRegisterNameMessage {
            get {
                return ResourceManager.GetString("IoCExceptionRegisterNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Windsor configuration registration should be done earlier than  any other type registration..
        /// </summary>
        internal static string IoCExceptionRegisterSectionFirstMessage {
            get {
                return ResourceManager.GetString("IoCExceptionRegisterSectionFirstMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoC error occured while trying to register types through a XML configuration section {0}. .
        /// </summary>
        internal static string IoCExceptionRegisterSectionMessage {
            get {
                return ResourceManager.GetString("IoCExceptionRegisterSectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoC error occured while trying to resolve all registered type {0}..
        /// </summary>
        internal static string IoCExceptionResolveAllMessage {
            get {
                return ResourceManager.GetString("IoCExceptionResolveAllMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoC error occured while trying to resolve type {0}..
        /// </summary>
        internal static string IoCExceptionResolveMessage {
            get {
                return ResourceManager.GetString("IoCExceptionResolveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoC error occured while trying to resolve type {0} with a specific name {1}..
        /// </summary>
        internal static string IoCExceptionResolveNamedMessage {
            get {
                return ResourceManager.GetString("IoCExceptionResolveNamedMessage", resourceCulture);
            }
        }
    }
}
